apiVersion: snapshot.kubevirt.io/v1beta1
kind: VirtualMachineRestore
metadata:
  name: database-vm-restore-01
  namespace: vm-snapshots
spec:
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: database-vm
  virtualMachineSnapshotName: database-vm-snapshot-01
