apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: webserver-custom
  namespace: vm-cloning-demo
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/domain: webserver-custom
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
          rng: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 4Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: webserver-custom-disk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              hostname: webserver-custom
              fqdn: webserver-custom.local
              manage_etc_hosts: true
              password: fedora123
              chpasswd: { expire: false }
              ssh_pwauth: true
              runcmd:
                - hostnamectl set-hostname webserver-custom
                - echo "<h1>Customized Clone</h1><p>Hostname: $(hostname)</p>" > /usr/share/nginx/html/index.html
                - systemctl restart nginx
          name: cloudinitdisk
