apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: webserver-production
  namespace: vm-cloning-production
  labels:
    environment: production
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/domain: webserver-production
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
            - disk:
                bus: virtio
              name: rootdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
          rng: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 8Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - name: rootdisk
          persistentVolumeClaim:
            claimName: webserver-production-disk
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              hostname: webserver-prod
              fqdn: webserver-prod.production.local
              manage_etc_hosts: true
              password: fedora123
              chpasswd: { expire: false }
              ssh_pwauth: true
              runcmd:
                - hostnamectl set-hostname webserver-prod
                - echo "<h1>Production Webserver</h1><p>Environment: Production</p>" > /usr/share/nginx/html/index.html
                - systemctl restart nginx
          name: cloudinitdisk
