apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-multi-boot
  namespace: boot-demo
spec:
  dataVolumeTemplates:
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: vm-multi-boot-primary
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: 30Gi
    - apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: vm-multi-boot-secondary
      spec:
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: 20Gi
  runStrategy: RerunOnFailure
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-multi-boot
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - disk:
                bus: virtio
              name: primarydisk
              bootOrder: 1
            - disk:
                bus: virtio
              name: secondarydisk
              bootOrder: 2
            - cdrom:
                bus: sata
              name: installcdrom
              bootOrder: 3
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
          rng: {}
        machine:
          type: pc-q35-rhel9.4.0
        memory:
          guest: 4Gi
      networks:
        - name: default
          pod: {}
      volumes:
        - dataVolume:
            name: vm-multi-boot-primary
          name: primarydisk
        - dataVolume:
            name: vm-multi-boot-secondary
          name: secondarydisk
        - name: installcdrom
          containerDisk:
            image: quay.io/containerdisks/fedora:latest
        - cloudInitNoCloud:
            userData: |-
              #cloud-config
              user: fedora
              password: fedora123
              chpasswd: { expire: False }
              ssh_pwauth: True
          name: cloudinitdisk
