apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm-numa-hugepages
  namespace: numa-hugepages-demo
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm-numa-hugepages
    spec:
      nodeSelector:
        cpumanager: "true"
      domain:
        cpu:
          sockets: 1
          cores: 2
          threads: 1
          dedicatedCpuPlacement: true
          isolateEmulatorThread: true
          numa:
            guestMappingPassthrough: {}
        memory:
          hugepages:
            pageSize: 2Mi
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 1Gi
        devices:
          autoattachMemBalloon: false
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        containerDisk:
          image: quay.io/containerdisks/fedora:latest
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: redhat
            chpasswd:
              expire: false
