apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hotplug-disk
  namespace: hotplug-demo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: lvms-vg1
  volumeMode: Block
