apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hpp-test-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: hostpath-csi
