apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: hpp-test-vm
  namespace: default
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/vm: hpp-test-vm
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        dataVolume:
          name: hpp-test-vm-rootdisk
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            user: fedora
            password: fedora
            chpasswd:
              expire: false
  dataVolumeTemplates:
  - metadata:
      name: hpp-test-vm-rootdisk
    spec:
      storage:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: hostpath-csi
      source:
        registry:
          url: docker://quay.io/containerdisks/fedora:latest
