apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: multi-disk-vm
  namespace: multi-disk-demo
spec:
  runStrategy: Always
  template:
    metadata:
      labels:
        kubevirt.io/domain: multi-disk-vm
    spec:
      domain:
        devices:
          disks:
          - name: rootdisk
            disk:
              bus: virtio
            bootOrder: 1
          - name: datadisk
            disk:
              bus: virtio
          - name: cloudinitdisk
            disk:
              bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 1Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - name: rootdisk
        dataVolume:
          name: multi-disk-rootdisk
      - name: datadisk
        dataVolume:
          name: multi-disk-datadisk
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |
            #cloud-config
            password: redhat
            chpasswd:
              expire: false
  dataVolumeTemplates:
  - metadata:
      name: multi-disk-rootdisk
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 30Gi
        storageClassName: lvms-vg1
      source:
        registry:
          pullMethod: node
          url: docker://quay.io/containerdisks/fedora:latest
  - metadata:
      name: multi-disk-datadisk
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: lvms-vg1-retain
      source:
        blank: {}
